[package]
name = "adventofcode2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
num-traits = "0.2.15"
petgraph = "0.6.2"
regex = "1.7.0"

[dev-dependencies]
rstest = "0.16.0"
